### ISSUE TITLE
这个是否是抄袭？

### ISSUE THREAD

**Issue by wying111** [hefuyicoder/ListenerMusicPlayer#12]
https://github.com/Allenhan123/ListenerMusicPlayer
http://www.jianshu.com/p/1ebef3483806
到底是谁抄袭啊= =

**Comment by HotBitmapGG** [comment]
看文章标题，写的分享而已，只不过文章里的地址他没有写原链接

**Comment by hefuyicoder** [comment]
@WangChangQin 谢谢你善意的提醒，我已联系文章作者修改。
