### ISSUE TITLE
找了两首歌都没成功下载歌词

### ISSUE THREAD

**Issue by tianshaokai** [hefuyicoder/ListenerMusicPlayer#17]

**Comment by hefuyicoder** [comment]
有些冷门的歌没有歌词是正常的，你下用薛之谦的演员试试？

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/23098053/596545fc-f67f-11e6-8279-9ae037d4f869.png)

**Comment by tianshaokai** [comment]
我看了一下是手机SD 卡里没有目录/Listener/lyric/，我自己创建了一个，就可以成功下载歌词了，播放中我关闭了屏幕，再次打开屏幕，就不显示歌词的播放进度了
