### ISSUE TITLE
App-crash happens if user refused permssion.

### ISSUE THREAD

**Issue by XinyueZ** [hefuyicoder/ListenerMusicPlayer#22]
The app will crash when the user refuses permission at begin of application.
I have sent a PR that fixed this crash, however, it is just a null-ptr-check not the problem source.

The problem head is focus-switch between different ```window```  if the permission-dialog shows.
You should check ```onWindowFocusChanged``` and ```checkPermissionAndThenLoad``` in ```MainActivity```  .

**Comment by hefuyicoder** [comment]
Thanks your PR, I debug just now and haven't good idea without  using null-ptr-check either
