### ISSUE TITLE
 Could not inflate Behavior subclass org.permutarku.musik.widget.RotationFabBehavior

### ISSUE THREAD

**Issue by zhiephie** [hefuyicoder/ListenerMusicPlayer#27]

**Comment by hefuyicoder** [comment]
It's my app's error really ? I am confused that the package name is not correct.

**Comment by zhiephie** [comment]
Yes, I'm try refactor the package name.

**Comment by hefuyicoder** [comment]
You refactor the package name ? And do you refactor the XML where it used ?

**Comment by zhiephie** [comment]
Yes, all your package name in java and xml refactoring. But only error in artist tab.

**Comment by hefuyicoder** [comment]
I guess there's some mistake while refactoring , is it all right before refactor?

**Comment by zhiephie** [comment]
Sure. 
O.k., I'm undo the package name. 

Thank you for reply.
