### ISSUE TITLE
请问如何解决

### ISSUE THREAD

**Issue by iammsf** [hefuyicoder/ListenerMusicPlayer#47]
在导入大佬的工程到Android Studio时IDE报错，粗略看来应该腾讯的部分插件404了。请问大佬这里还有备份吗？

Error:Could not find com.tencent.mm:AndResGuard-gradle-plugin:1.2.0.
Searched in the following locations:
    https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.0/AndResGuard-gradle-plugin-1.2.0.pom
    https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.0/AndResGuard-gradle-plugin-1.2.0.jar
Required by:
    :MDMusicPlayer:unspecified

**Comment by iammsf** [comment]
打扰了哈哈哈，去仓库里看了一下，原来是作者已经删除了1.2.0和之前的版本，手动更改gradle依赖里面的版本之后重新同步gradle就可以了

**Comment by zhkingzh** [comment]
> 打扰了哈哈哈，去仓库里看了一下，原来是作者已经删除了1.2.0和之前的版本，手动更改gradle依赖里面的版本之后重新同步gradle就可以了

你好，请问是怎么改的？能具体一些吗？我也碰到这个问题了

**Comment by PandarMan** [comment]
大哥你手动更改到 哪个版本呀

**Comment by iammsf** [comment]
@CCCCCCCCOOL
去掉最后一个斜杠后面的文件名，就是软件仓库的网页地址了。

**Comment by iammsf** [comment]
@CCCCCCCCOOL
更正一下，是最后两个斜杠后面的内容

**Comment by PandarMan** [comment]
好的，非常感谢
