### ISSUE TITLE
应用安装不上，闪退

### ISSUE THREAD

**Issue by xiaoDongBei90** [hefuyicoder/ListenerMusicPlayer#5]
还有一个问题就是，歌手那个fragment，里面的条目点击进去，展示的是一个activity还是fragment。你是怎样保证下面的迷你音乐条不动的？

**Comment by hefuyicoder** [comment]
安装上了么？点进去展示的是一个fragment，这样就能轻松地保持下面的迷你音乐条不动了。其实使用activity也可以，轻听就是这么做的，不过转跳时迷你音乐条会闪一下。

**Comment by liuhui19991** [comment]
安卓19-22有问题,因为权限问题,修改PermissionManager下的checkPermission方法返回值改为  
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
            return PackageManager.PERMISSION_GRANTED == context.checkSelfPermission(permissionName);
        else return true;

**Comment by hefuyicoder** [comment]
好的，谢谢你的反馈
